### ISSUE TITLE
高分2号和QB的卫星参数

### ISSUE THREAD

**Issue by stxg13056** [liangjiandeng/DLPan-Toolbox#20]
您好，我在使用MATLAB工具进行传统方法计算比较的时候，TV方法需要使用到卫星一些参数值，但是代码里没有给出GF2和QB的卫星参数，想请问一下方便提供一下吗？
![image](https://github.com/liangjiandeng/DLPan-Toolbox/assets/81797325/ae93c319-62ae-41e8-a8cf-5f3571402beb)

**Comment by liangjiandeng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    QB的参数：        %%%%%%%%%%%%%%%%%%%%%%%%%% Parameters setting %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        switch sensor
            case {'IKONOS','QB'}
                w=[0.1091    0.2127    0.2928    0.3854];
                c = 8;
                alpha=1.064;
                maxiter=10;
                lambda = 0.47106;
            case {'GeoEye1','WV4'}
                w=[0.1552, 0.3959, 0.2902, 0.1587];
                c = 8;
                alpha=0.75;
                maxiter=50;
                lambda = 157.8954;
            case 'WV3'
                w=[0.0657    0.1012    0.1537    0.1473    0.1245    0.1545    0.1338    0.1192];
                c = 8;
                alpha=0.75;
                maxiter=50;
                lambda = 1.0000e-03;            case 'GF2'                w=[0.25 0.25 0.25 0.25];                c = 8;                alpha=0.75;                maxiter=50;                lambda = 1.0000e-03;         endGF2的alpha, maxiter, 和lambda可以自己调节到最优。。祝好
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liangjian.deng
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年07月15日 14:28
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [liangjiandeng/DLPan-Toolbox] 高分2号和QB的卫星参数 (Issue #20)
        
      
    
  
  
您好，我在使用MATLAB工具进行传统方法计算比较的时候，TV方法需要使用到卫星一些参数值，但是代码里没有给出GF2和QB的卫星参数，想请问一下方便提供一下吗？


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
